---
title: "Summaries week 8"
subtitle: "Phonetics and Phonology of Bilingualism"
author: "Meritxell Feliu Ribas"
date: "2024-03-15"
output: pdf_document
---

# Reading 1: Bradlow (1995)
Bradlow (1995) compared the acoustic vowel systems of General American English and Madrid Spanish (plus Greek) in order to examine the effect of inventory size, as English vowel system is larger than that of Spanish (and Greek). To that end, she analyzed vowel formant measurements (F1 and F2) from vowels that occurred between voiceless plosives (/p,t,k/), elicited from 8 participants (4 English and 4 Spanish speakers, respectively) in a read aloud task. Whereas English vowels had higher F2 values, indicating a different tongue position, there were no significant differences between languages as for F1 values. Data from Spanish were compared to Greek (both have 5 monophthongs), showing that Spanish vowels had generally higher F2 and lower F1 values. In addition, the acoustic vowel space of English had a larger area, but it was dependent on the syllabic context, and there were no significant differences between point and nonpoint vowels in any of the tested languages. These results support the idea of language-specific constraints in the production of vowels and their acoustic space (language-specific base-of-articulation property). 

**Reference:** Bradlow, A. R. (1995). “A comparative acoustic study of english and spanish vowels". In: *The Journal of the Acoustical Society of America* 97.3, pp. 1916–1924.



# Reading 2: Højen and Flege (2006)
I am the discussion leader for this article.

**Reference:** Højen, A. and J. E. Flege (2006). “Early learners’ discrimination of second-language vowels". In: *The Journal of the Acoustical Society of America* 119.5, pp. 3072–3084.



# Reading 3: Celdrán and Elvira-García (2019)
This is a chapter from the book *Key Issues in the Teaching of Spanish Pronunciation*. According to the syllabus, no summary is required for chapters.

**Reference:** Celdrán, E. M. and W. Elvira-Garcia (2019). “Description of Spanish Vowels and Guidelines for teaching them".In: *Key Issues in the Teaching of Spanish Pronunciation*. Ed. by R. Rao. Routledge, pp. 17–39.


# Notes on Højen and Flege (2006)
  * General topic: Perception of L2 sounds 
  
  * More specific: The discrimination of English vowels by L1 Spanish - L2 English early bilinguals (learners*)
      * Me parece curioso el hecho de que los llamen "early learners" y no "early bilinguals". Sé que es solo terminología, pero bueno... 
      * Asimismo, llaman a los ML de la L2, L2 native speakers, which also confusing for me. 
  
  * Background lit.:
    * Infants begin to perceive speech in a language-specific way during the first year of life, when they develop perceptual processes specialized for the ambient language (when they are born, they can discriminate all sounds, from all languages) -> Shift from a language-general to a language-specific pattern of perception 
    * It has been proposed that, as people grow older, L2 learning is hindered by a loss of neuroplasticity that accompanies normal neural maturation -> L2 speech acquisition is impeded by the acquisition of the L1 phonological system.
    * Native Language Magnet theory (NLM theory): 
        * tries to explain what exactly happens (see bullet points above) and why
        * holds that...
            * infants categorize sound patterns into a “perceptual map" ("sound map")
            * babies create perfect examples of sounds with a target area around each sound
            * these prototypes “tune” the child’s brain to the native language (statistical learning?)
            * once a sound category exists in memory, “it functions like a magnet for other sounds” (Kuhl, 2000, p. 11853). That is, the prototype attracts sounds that are similar so that they sound like the prototype itself
            * thus, the identification of L1 speech sounds become more robust; L2 categories may become difficult (L2 learning as more challenging)
        * describes how innate factors and early experience with language interact in the development of speech perception 
        * Some evidence suggest that this "sound map" may be difficult to reverse (L1 Spanish - L2 Catalan), whereas others point to the opposite direction (L1 Italian - L2 Canadian English) -> Conflicting results: L1 use, testing techniques, age of participants, type of input (L2 accented or not), etc.
            * ADD THIS AS A QUESTION; E.G., CAN THIS SOUND MAP BE REVERSED BASED ON THE STUDIES DISCUSSED IN THE LIT REVIEW SECTION? 
    * Bosch et al. (2000), Pallier et al. (1997, 2001), Sebastián-Gallés and Soto-Faraco (1999), Sebastián-Gallés et al. (2005)
        * Early learners obtained significantly lower scores than Catalan native speakers, and showed a wider range of scores (/e/ vs /ɛ/)
        - Main conclusions:
        * "the speech perception system doesn't seem able to easily develop new phonetic categories after perceptual attunement to the L1 phonological system"
        * "early learners exhibit a lack of behavioral plasticity with respect to learning to perceive contrastive phonemes of an L2"
        * "there are severe limitations to the malleability of the initially acquired L1 phonemic categories even under conditions of early and extensive exposure"
        * SO... early learners are unlikely to perceive L2 vowels in a nativelike way
    * Flege et al. (1999), Flege and MacKay (2004)
        * Low-L1-use group and English ML got similar results in a discrimination task of English vowels; high-L1-use group differed marginally from MLs.
        - Main conclusions:
        * "early exposure to the L2 does not guarantee the formation of new phonetic categories for L2 vowels, but that category formation will be more likely for individuals who use their L1 infrequently"
        * SO... early learners may closely resemble L2 native speakers, if they use their L1 infrequently
    * A raíz de estos conflicting results, surge the present study! :) 
  
  * The present study:
    * Previous research showed two different trends/patterns: 
        (1) early learners differed significantly from the control group (L2 native speakers), SO... they are unlikely to perceive L2 vowels in a nativelike way
        (2) early learners did not  significantly differ from the control group (L2 native speakers), SO... they may closely resemble L2 native speakers, if they use their L1 infrequently
    * About Højen and Flege (2006)
        * Goal: to examine the discrimination of English vowels by L1 Spanish - L2 English early bilinguals (learners*)
        * But... What is the novelty of this study? 
            * They assessed early learners' perceptual learning by comparing their performance to that of 2 control groups: English MLs and Spanish MLs
        * And what is the reasoning behind this change in methods?
            * English MLs -> to know if their perceptual learning is complete
            * Spanish MLs -> to determine how much they had learned, even in the absence of complete learning
        * 2 experiments
  
  
  * Experiment 1:
    * Aim: to develop an AXB test that would result in higher (near-ceiling) scores for vowels heard as distinct phonemes and lower (near-chance) scores for foreign vowels that might be heard as belonging to the same category in the L1.
        * e.g., in Catalan, for L1 Spanish: [u] - [o]; [e] vs [ɛ]
        * Why is it important? 
            * para asegurarse de que no lo acierten "a potra", es decir, miran cómo hacer la tarea más difícil para evitar que los resultados estén hinchados por hacerlo a boleo -> to better assess L2 vowel discrimination abilities
            * it often produces very high discrimination scores (90%-100% correct) for pairs of foreign vowels that are likely perceived as instances of a single phonetic category in the listener's native language (L1)
            * if the Spanish monolingual group achieves near-ceiling scores due to non-phonetic encoding strategies (above change can be due to context codes -> the listener positions each stimulus in relation to the full range of stimuli presented in the experiment), they cannot effectively serve as a baseline
            * 3 different processess in the discrimination of speech sounds as wiether wihtin- or between-category contrasts might be used: labeling, context coding, trace coding
            
    * What is an AXB test?
        * a type of perceptual discrimination task
        * participants listen to three stimuli: A, X, and B
        * they determine whether X sounds more like A or B
        
    * Participants: 45 English monolinguals; 3 native speakers of Danish
    
    * Stimuli: nonwords (CCVC) with 4 vowel contrasts inserted:
        * easy contrast: [] - [] -> /gl_s/
        * difficult contrasts: 
            * [] - [] -> /fl_s/
            * [] - [] -> /kl_s/
            * [] - [] -> /tj_s/
        * 3 conditions:
            * blocked: contrasts were presented in separate blocks (small stimulus range) -> All stimuli in declarative sentences: "Det hed virkelig __ engang"
            * mixed: contrasts were randomly presented in one large block (large stimulus range) -> All stimuli in declarative sentences: "Det hed virkelig __ engang"
            * mixed/F0: one large block + variation in F0 (high vs low F0):
                * Half stimuli in declarative sentences ("Det hed virkelig __ engang") and the other half in interrogative sentences ("Hed det virkelig __ engang?") 
                * La variación en el pitch se consigue con el uso de declarative vs interrogative sentences (lower vs higher pitch, respectively)
                * Inclusion of different F0 patterns:
                    * no F0 change (HHH; LLL)
                    * neutral trials (HLH; LHL) -> f0 of X (target) is different than its match and mismatch
                    * congruent trials (HHL; LLH; HLL; LHH) -> f0 of X is the same as the f0 of its "match"
                    * incongruent trials -> f0 of X is different than the f0 of its "match"
                    
    * Procedure:
        * 64 trials x 4 contrasts = 256 AXB trials
        * 3 stimuli 
        * push 1-2 or 2-3 button (1-2 if 2 was like 1, 2-3 if 2 was like 3)
        * practice block with feedback
        
    * Results:
      * Danish MLs had higher scores in all conditions (easy and difficult)
      * English MLs had higher scores in the easy condition, and substantially lower scores in the difficult conditions, but still above chance. However, they were lowered in the mixed/F0 condition compared to the blocked condition (and especially lowered in f0 incongruent trials; for neutral was inbetween congruent and incongruent). Interestingly, there were no significant differences between the blocked and the mixed conditions, which suggests that the differences between the blocked and the mixed/f0 was due to F0 manipulation. So, f0 seemed to have an effect on lowering the scores ("more difficult").
      * HENCE, they decided to use the mixed/f0 condition for experiment 2, considering only incongruent (target different as matched) and neutral f0 (target different as both matched and mismatched) types.

* What is the difference between a CDT and a AXB test?
        (1) Stimulus presentation:
              * In a CDT, participants typically hear two stimuli sequentially and are asked to determine whether they are the same or different. The stimuli are usually from different phonetic categories.
              * In an AXB test, participants hear three stimuli sequentially (labeled A, X, and B) and are asked to determine whether X sounds more like A or B. The X stimulus may be from the same category as A or B, and the task is to discriminate between the two categories.
        (2) Task complexity:
              * CDTs tend to be simpler tasks because participants only need to judge whether two stimuli are the same or different.
              *AXB tests can be more complex because participants must not only discriminate between stimuli but also compare them to two reference stimuli (A and B) to make their judgment.
        (3) Purpose:
              * CDTs are often used to measure sensitivity to phonetic contrasts and categorical perception, i.e., how individuals categorize speech sounds into distinct phonetic categories.
              * AXB tests are used to assess discrimination abilities between speech sounds, particularly when stimuli are drawn from similar phonetic categories or when the task involves categorical perception.
  
  * Experiment 2:
    * Aim:
        * to analyze the discrimination of English vowels by adult L1 Spanish - L2 early learners of English and compare it to that of English monolinguals (and Spanish monolinguals)
        
    * Methodology:
        * Participants (n=60):
            * 20 L1 Spanish - L2 English early bilinguals
            * 20 English monolinguals
            * 20 Spanish monolinguals
        * Materials:
            * (Language background questionnaire)
            * (Production task)
            * Perception task
        * Stimuli: 
            * English nonwords (CCVC) with 4 vowel contrasts:
                * easy contrast: [i] - [u] -> /gl_s/
                * difficult contrasts: 
                    * [ʊ] - [oʊ]* -> /fl_s/
                    * [ɪ] - [eɪ]* -> /kl_s/
                    * [ɑ] - [ʌ] -> /tʃ_s/
            * Foto (fig. 2)
            * Declarative (low-f0) and interrogative sentences (high-f0)
            * Neutral f0 type and incongruent f0 type
    
    * Procedure:
        * 64 trials x 4 contrasts = one block of 256 trials
        * ISI of 0 or 1000 ms -> "the block containing all 256 trials was presented two times in counterbalanced order with an ISI of either 0 or 1000 ms"
        * 3 stimuli 
        * push 1-2 or 2-3 button (1-2 if 2 was like 1, 2-3 if 2 was like 3)
        * practice block with feedback
        
    * Results: 
        * Overall, scores were significantly lower in the incongruent f0 condition - similar effect across the 3 groups
        * Overall, scores were lower, on average, for ISI=0 ms than ISI=1000 ms
            * English MLs scored near ceiling for the difficult contrasts
            * Spanish MLs scored near chance for the difficult contrasts
            * BLs obtained significantly higher scores than Spanish MLs at both ISIs
            * BLs didn't differ from English MLs for any contrast at ISI=1000 ms
            * BLs scored lower than English MLs for two difficult contrasts at ISI=0 ms (suggesting that long-term memory representations for English vowels were not identical to the English MLs')
            * Scores obtained for individual BLs and Spanish MLs for the three difficult contrasts were non-overlapping at ISI=0ms, which provides evidence of extensive perceptual learning in early learners -> It is inconsistent with the view that speech perception system loses plasticity and that new phonetic categories become unlikely following attunement to the L1 sound system
        * Easy contrast: higher scores than in the difficult contrast, but...
            * BLs' scores were slightly lower than those of English MLs
            * BLs' scores were significantly higher than those of Spanish MLs
        * Difficult contrast:
            * Spanish MLs' scores were all near chance
            * BLs' scores were lowered than those of English MLs in []-[] and []-[]. Importantly, these scores were more similar to those of English MLs than those of Spanish MLs
        * Individual differences among BLs:
            * 3 of the lowest-scoring BLs had a later AoE, compared to the highest-scoring BLs -> Age of Exposure
            * 3 of the highest-scoring BLs reported using English more with friends in the past 5 years and during the first 5 years of exposure to English, compared to the lowest-scoring BLs -> L2 use
            * 3 of the 4 highest-scoring BLs reported having attended school in the U.S. longer, compared to the lowest-scoring BLs -> L2 exposure
            * Differences in AoE and L2 might be responsible for important individual differences among BLs
        
    * Discussion: 
        * The vowel pair in the easy contrast was heard as distinct Spanish vowels for Spanish MLs
        * Each vowel pair in the difficult contrast was heard as a single Spanish vowel category for Spanish MLs -> They could not discriminate between them, although they were different in English
        * Important individual differences among BLs -> No es un grupo homogéneo!
        * Factors that may influence L2 speech perception: amount of L2 input, type of L2 input, L2 use, age of first exposure to the L2 -> Age effects might exist
        * BLs can show nativelike discrimination of English vowel contrasts
        * However, some BLs obtained scores below English ML -> Early exposure to an L2 doesn't guarantee nativelike discrimination of L2 phonetic segments -> There might be other factors that influence such perception
  
  
  * Potential questions:
    * What kind of studies are described in the background literature? How do they inform the present study?
    * What have previous studies on the perception of word stress found?
    * What is the topic of analysis? 
    * Why do they focus on the vowels [a] and [i]? Why unaccented contexts?
    * Why did the authors choose to manipulate duration, overall intensity, and spectral tilt as potential cues to stress?
    * What might explain the differential perception of stress contrast depending on vowel type ([a] vs. [i])?
    * What are your main takeaways of this study? Why is it important? How do the findings in this study contribute to our knowledge of L2 perceptual abilities? 
  * What are the implications of these findings for both teaching and learning?
  * How might future research build upon these findings to further investigate perception of L2 sounds (Spanish, English, other languages)?

