---
title: "Dominance, proficiency, and Spanish heritage speakers' production of English and Spanish vowels"
subtitle: "Christine Shea (2017)"
author: "Meritxell Feliu Ribas"
institute: "Rutgers University"
date: "2024/03/25"
output:
  xaringan::moon_reader:
    css: [default, rutgers, rutgers-fonts]
---
# Summary 

+ **General topic**: Production of L1-L2 sounds
+ **More specific**: The production of Spanish and English vowels by Spanish heritage speakers (HS)
---

# Summary 

+ **General topic**: Production of L1-L2 sounds
+ **More specific**: The production of Spanish and English vowels by Spanish heritage speakers (HS)

<br/>

# Some key concepts

+ Dominance vs Proficiency
+ Domains of dominance vs Dimensions of dominance
+ Incomplete acquisition vs Attrition
+ Divergent attainment
+ Structural simplicity

---
# Previous studies
+ Not many studies are mentioned, main focus on HSs and their different outcomes (proficiency, dominance)
+ Studies on vowel production:
    + Konopka & Pierrehumbert (2008)
    + Ronquest (2012)
+ .black[Question]: What makes this study different (e.g., participants profile, stimuli, predictors, statistical analysis)?

---
# Previous studies
+ Not many studies are mentioned, main focus on HSs and their different outcomes (proficiency, dominance)
+ Studies on vowel production:
    + Konopka & Pierrehumbert (2008)
    + Ronquest (2012)
+ .black[Question]: What makes this study different (e.g., participants profile, stimuli, predictors, statistical analysis)?


# The present study
+ Main goals:
  + Examine Spanish HSs' vowel productions in both Spanish and English
  + Explore how different factors related to dominance and proficiency account for the variability observed in vowel production
  + Demonstrate that HSs' dominance and proficiency in each language reflect the experience and knowlege particular to that language

---
# Methods

### Participants
+ 15 L1 Mexican Spanish - L2 English early bilinguals
+ 15 L1 Mexican (n=9) or Colombian (n=6) Spanish - L2 late learners of English
+ 15 L1 English - L2 late learners of Spanish

<br/>

### Materials
+ (Language background questionnaire)
+ Fluency tasks (2 monologues)
+ Expressive One Word Picture Vocabulary Test
+ Picture naming task
+ Production task

---
### Production task
+ Participants had to read a **list of words**, separated into rows
+ Each row had **4 words**: 3 disyllabic, troichaic real words + 1 nonword
    + The target vowel was contextualized in the frame "bVpa" in the nonword
    + e.g., [i] **&rarr;** *beepa*
+ **Target vowels**
    + English:[i ɪ &#603; e æ &#593; ʌ o ʊ u]
    + Spanish: [i e a o u]
+ **F1 and F2** measurements for each target vowel
+ Vowels were **normalized** (speaker intrinsic, speaker intrinsic, formant intrinsic) **&rarr;** Calculation of Pillai scores

### Analysis
+ **Dependent variable**: Pillai scores
+ **Predictors**: 
    + 4 measures of language dominance
    + 3 measures of language proficiency
  + .black[Question]: What specific measures for evaluating language dominance and proficiency do they use?

---
# Main results

### Pilai scores
+ Divergence in Pillai scores
+ More compact for Spanish than English  **&rarr;** Greater overlap for Spanish vowels than for English 
+ Differences between tense and lax and low vowels for English:
    + Higher scores for the lax [ɪ &#603; æ ʌ ʊ] and low vowel [&#593;] than for the tense [i e o u] **&rarr;** Less overlap with the nonheritage English speakers

---
### Dominance
+ Factors made **different unique and common contributions** 
+ Greatest unique contribution for both languages, but different proportion: **Spanish outside the home** (Span: 40%, Eng: 26%)
+ In **Spanish**, Spanish outside the home was followed by shared variance Spanish inside - Spanish outside the home
    + Spanish inside the home &rarr; small unique contribution (highly correlated with Spanish outside the home)
+ In **English**, Spanish outside the home was followed by unique contribution of English AoA 
    + English AoA accounted for a larger proportion of the variance in the English Pillai scores than in Spanish **&rarr;** Spanish phonetic categories may have influenced the development of English and affected the lax vowels (less overlap), which are not part of the Spanish inventory

---
### Proficiency
+ Similar to in the dominance model, **different factors** accounted for the variability in each language
+ Unique contributions, different proportion:
    + **Adult monologue score** (Span: 17%, Eng: 7%)
    + **Picture naming score** (Span: 15%, Eng: 8%)
+ In **Spanish**, vocabulary knowledge accounted for 16% of the unique variance (0% in English)
+ In **Spanish**, adult monologue, picture naming, vocabulary tasks made unique contributions to the model variance that summed to almost 50% of the total; in **English** the unique variance of the four proficiency factors summed to only 15%
+ This model accounted for a much higher % of variability in Pillai scores than did dominance

+ .black[Question]: Why do you think that the proficiency model accounted for a  higher % of variability in Pillai scores?
+ .black[Question]: What do these results (dominance and proficiency) indicate?

---
# Conclusions
+ **Different factors** accounted for unique and shared variance across each language **&rarr;** Factors that best account for variability in HL proficiency will not necessarily be the same as those that reflect variability in the majority community language **&rarr;** This is **not surprising** considering the reality of HSs' language experience
+ Proficiency and dominance are constructs that rest upon a **complex set of factors**, which may interact differently for each of the HS's languages
+ **Dominance model** **&rarr;** There might be **other factors at play** when capturing the notions of dominance that were not fully accounted for by the four examined variables
+ Greater explanatory power of **proficiency** **&rarr;** It might be **easier to measure**
+ Each of the **HSs' languages develops under different conditions** and **variability** across HS phonetic productions is to be expected

+ .black[Question]: What are your main takeaways of this study? 
